import { Inter } from "next/font/google";
import "./globals.css";
import HeaderLayout from "./header";
import Menu from "./menu";
import TopLeftImg from "./components/topLeftImg";
import BottomRightImg from "./components/bottomRightImg";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className="bg-[#0c0c20]">
      <head></head>
      <body className={`${inter.className} h-full w-full`}>
        <HeaderLayout />
        <TopLeftImg />
        <BottomRightImg />
        <Menu />
        {children}
      </body>
    </html>
  );
}
